spring:
  config:
    import: optional:file:.env.properties, classpath:application-${spring.profiles.active}.yml
  profiles:
    active: local

server:
  port: 8082

jwt:
  header: Authorization
  secret: a3d8e74d1eafebc3a80403d04c453afd0da30eb54d1111125bc6a26ad38eed6c
  token-validity-in-seconds: 86400

sns:
  google:
    url: ${GOOGLE_URL} # 고정값
    client:
      id: ${GOOGLE_ID}
      secret: ${GOOGLE_SECRET}
    callback:
      url: ${GOOGLE_CALLBACK_URL}
    token:
      url: ${GOOGLE_TOKEN_URL} # 고정값

  kakao:
    url: ${KAKAO_URL} # 고정값
    client:
      id: ${KAKAO_ID} # REST API KEY
      secret: ${KAKAO_SECRET} # SECRET KEY
    callback:
      url: ${KAKAO_CALLBACK_URL}
    token:
      url: ${KAKAO_TOKEN_URL} # 고정값